deleted the secops

diff --git a/.github/workflows/cicd.yml b/.github/workflows/cicd.yml
--- a/.github/workflows/cicd.yml
+++ b/.github/workflows/cicd.yml
@@ -1,5 +1,4 @@
 name: Bank Backend Pipeline
-
 on:
   push:
     branches:
@@ -9,7 +8,6 @@ on:
   # pull_request:
   #   branches:
   #     - cicd
-
 jobs:
   Continues-Integration_build_and_push:
     runs-on: ubuntu-latest
@@ -18,45 +16,35 @@ jobs:
       ECR_REPOSITORY: bank-backendapi
       AWS_REGION:  us-east-1
       IMAGE_TAG: ${{ github.run_number }}
-
     steps:
     - name: Checkout repository
       uses: actions/checkout@v4
-
     - name: Set up Docker Buildx
       uses: docker/setup-buildx-action@v3
-
     - name: Configure AWS credentials
       uses: aws-actions/configure-aws-credentials@v4
       with:
         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
         aws-region: ${{ env.AWS_REGION }}
-
     - name: Log in to Amazon ECR
       id: login-ecr
       uses: aws-actions/amazon-ecr-login@v2
-
     - name: Build Docker image
       run: |
-        docker build -t ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }} . 
-
-  
-    - name: Push Docker images to ECR
+        docker build -t ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }} .
+    - name: Push Docker image to ECR
       run: |
-        docker push ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }} 
-
-
+        docker push ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }}
     - name: Clean up Docker images locally
       if: always()
       run: |
         docker rmi ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }} || true
-        docker rmi ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:latest || true
 
-  
   Continues-Update_k8s_manifest:
     runs-on: ubuntu-latest
     needs: Continues-Integration_build_and_push
+    if: github.ref == 'refs/heads/main'
     env:
       ECR_REGISTRY: 547268988762.dkr.ecr.us-east-1.amazonaws.com
       ECR_REPOSITORY: bank-backendapi
@@ -71,12 +59,9 @@ jobs:
          cd Bank-Kubernetes-Manifest
          git config --global user.email "dirachukwu@gmail.com"
          git config --global user.name "lilian"
-
          sed -i "s+${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:.*+${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }}+g" ./bank-project/backendapi.yaml
-
-         cat ./bank-project/backendapi.yaml | grep -q "${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }}"
-
+         grep -q "${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }}" ./bank-project/backendapi.yaml \
+           || { echo "Image tag update failed!"; exit 1; }
          git add bank-project/backendapi.yaml
          git commit -m "Update backendapi image to version ${{ env.IMAGE_TAG }}"
          git push origin main
-        
